import type { ProductDetail } from "@/products/types/product.types";

export const mockProducts: ProductDetail[] = [
  {
    id: "1",
    brand: "TechMobile",
    model: "Neo X Pro",
    price: 899,
    imageUrl: "https://itx-frontend-test.onrender.com/images/Jz_TwlgtO8UiNZBfb72A3.jpg",
    cpu: "Snapdragon 8 Gen 3",
    ram: "12GB",
    os: "Android 15",
    screenResolution: "1440x3200",
    battery: "5000mAh",
    cameras: "200MP+50MP+12MP",
    dimensions: "164.3x75.8x8.9mm",
    weight: "210g",
    storageOptions: [
      { code: "128", name: "128GB" },
      { code: "256", name: "256GB" },
      { code: "512", name: "512GB" },
    ],
    colorOptions: [
      { code: "black", name: "Black", hexColor: "#1a1a1a" },
      { code: "silver", name: "Silver", hexColor: "#e8e8e8" },
      { code: "blue", name: "Ocean Blue", hexColor: "#2563eb" },
    ],
  },
  {
    id: "2",
    brand: "Apple",
    model: "iPhone 17 Pro",
    price: 1299,
    imageUrl: "https://itx-frontend-test.onrender.com/images/Jz_TwlgtO8UiNZBfb72A3.jpg",
    cpu: "A19 Bionic",
    ram: "8GB",
    os: "iOS 20",
    screenResolution: "1290x2796",
    battery: "4500mAh",
    cameras: "48MP+48MP+48MP",
    dimensions: "149.6x71.5x8.25mm",
    weight: "199g",
    storageOptions: [
      { code: "256", name: "256GB" },
      { code: "512", name: "512GB" },
      { code: "1000", name: "1TB" },
    ],
    colorOptions: [
      { code: "natural", name: "Natural Titanium", hexColor: "#d4c9b8" },
      { code: "white", name: "White Titanium", hexColor: "#f0f0f0" },
      { code: "black", name: "Black Titanium", hexColor: "#2d2d2d" },
    ],
  },
  {
    id: "3",
    brand: "Samsung",
    model: "Galaxy S26 Ultra",
    price: 1399,
    imageUrl: "https://itx-frontend-test.onrender.com/images/Jz_TwlgtO8UiNZBfb72A3.jpg",
    cpu: "Exynos 2600",
    ram: "16GB",
    os: "Android 15",
    screenResolution: "1440x3120",
    battery: "5500mAh",
    cameras: "200MP+50MP+12MP+10MP",
    dimensions: "163.4x78.1x8.6mm",
    weight: "228g",
    storageOptions: [
      { code: "256", name: "256GB" },
      { code: "512", name: "512GB" },
      { code: "1000", name: "1TB" },
    ],
    colorOptions: [
      { code: "titanium", name: "Titanium Gray", hexColor: "#8c8c8c" },
      { code: "green", name: "Jade Green", hexColor: "#4ade80" },
      { code: "white", name: "Pearl White", hexColor: "#fafafa" },
    ],
  },
  {
    id: "4",
    brand: "Google",
    model: "Pixel 11 Pro",
    price: 999,
    imageUrl: "https://itx-frontend-test.onrender.com/images/Jz_TwlgtO8UiNZBfb72A3.jpg",
    cpu: "Tensor G6",
    ram: "12GB",
    os: "Android 15",
    screenResolution: "1344x2992",
    battery: "4800mAh",
    cameras: "50MP+48MP+48MP",
    dimensions: "152.8x72.9x8.6mm",
    weight: "206g",
    storageOptions: [
      { code: "128", name: "128GB" },
      { code: "256", name: "256GB" },
    ],
    colorOptions: [
      { code: "obsidian", name: "Obsidian", hexColor: "#1c1c1c" },
      { code: "hazel", name: "Hazel", hexColor: "#a8a29e" },
      { code: "rose", name: "Rose", hexColor: "#f43f5e" },
    ],
  },
  {
    id: "5",
    brand: "OnePlus",
    model: "Open 2",
    price: 1099,
    imageUrl: "https://itx-frontend-test.onrender.com/images/Jz_TwlgtO8UiNZBfb72A3.jpg",
    cpu: "Snapdragon 8 Gen 3",
    ram: "16GB",
    os: "Android 15",
    screenResolution: "2268x2440",
    battery: "4800mAh",
    cameras: "48MP+48MP+64MP",
    dimensions: "153.4x73.3x8.7mm",
    weight: "239g",
    storageOptions: [
      { code: "256", name: "256GB" },
      { code: "512", name: "512GB" },
    ],
    colorOptions: [
      { code: "black", name: "Voyager Black", hexColor: "#0a0a0a" },
      { code: "green", name: "Emerald Green", hexColor: "#059669" },
    ],
  },
  {
    id: "6",
    brand: "Xiaomi",
    model: "15 Ultra",
    price: 799,
    imageUrl: "https://itx-frontend-test.onrender.com/images/Jz_TwlgtO8UiNZBfb72A3.jpg",
    cpu: "Snapdragon 8 Gen 3",
    ram: "16GB",
    os: "HyperOS 2.0",
    screenResolution: "1440x3200",
    battery: "5300mAh",
    cameras: "50MP+50MP+50MP+50MP",
    dimensions: "161.2x75.3x9.2mm",
    weight: "224g",
    storageOptions: [
      { code: "256", name: "256GB" },
      { code: "512", name: "512GB" },
    ],
    colorOptions: [
      { code: "white", name: "Ceramic White", hexColor: "#f8f8f8" },
      { code: "black", name: "Ceramic Black", hexColor: "#1a1a1a" },
    ],
  },
  {
    id: "7",
    brand: "Nothing",
    model: "Phone (4)",
    price: 599,
    imageUrl: "https://itx-frontend-test.onrender.com/images/Jz_TwlgtO8UiNZBfb72A3.jpg",
    cpu: "Snapdragon 8 Gen 2",
    ram: "12GB",
    os: "Nothing OS 4.0",
    screenResolution: "1080x2412",
    battery: "4700mAh",
    cameras: "50MP+50MP",
    dimensions: "152.2x75.5x8.3mm",
    weight: "193g",
    storageOptions: [
      { code: "128", name: "128GB" },
      { code: "256", name: "256GB" },
    ],
    colorOptions: [
      { code: "white", name: "White", hexColor: "#f5f5f5" },
      { code: "yellow", name: "Yellow", hexColor: "#eab308" },
    ],
  },
  {
    id: "8",
    brand: "Sony",
    model: "Xperia 1 VII",
    price: 1199,
    imageUrl: "https://itx-frontend-test.onrender.com/images/Jz_TwlgtO8UiNZBfb72A3.jpg",
    cpu: "Snapdragon 8 Gen 3",
    ram: "12GB",
    os: "Android 15",
    screenResolution: "1644x3840",
    battery: "5000mAh",
    cameras: "48MP+48MP+48MP",
    dimensions: "165.3x71.3x8.3mm",
    weight: "192g",
    storageOptions: [
      { code: "256", name: "256GB" },
      { code: "512", name: "512GB" },
    ],
    colorOptions: [
      { code: "black", name: "Black", hexColor: "#1a1a1a" },
      { code: "purple", name: "Violet", hexColor: "#7c3aed" },
    ],
  },
  {
    id: "9",
    brand: "Sony",
    model: "Xperia 1 VII",
    price: 1199,
    imageUrl: "https://itx-frontend-test.onrender.com/images/Jz_TwlgtO8UiNZBfb72A3.jpg",
    cpu: "Snapdragon 8 Gen 3",
    ram: "12GB",
    os: "Android 15",
    screenResolution: "1644x3840",
    battery: "5000mAh",
    cameras: "48MP+48MP+48MP",
    dimensions: "165.3x71.3x8.3mm",
    weight: "192g",
    storageOptions: [
      { code: "256", name: "256GB" },
      { code: "512", name: "512GB" },
    ],
    colorOptions: [
      { code: "black", name: "Black", hexColor: "#1a1a1a" },
      { code: "purple", name: "Violet", hexColor: "#7c3aed" },
    ],
  },
  {
    id: "10",
    brand: "Sony",
    model: "Xperia 1 VII",
    price: 1199,
    imageUrl: "https://itx-frontend-test.onrender.com/images/Jz_TwlgtO8UiNZBfb72A3.jpg",
    cpu: "Snapdragon 8 Gen 3",
    ram: "12GB",
    os: "Android 15",
    screenResolution: "1644x3840",
    battery: "5000mAh",
    cameras: "48MP+48MP+48MP",
    dimensions: "165.3x71.3x8.3mm",
    weight: "192g",
    storageOptions: [
      { code: "256", name: "256GB" },
      { code: "512", name: "512GB" },
    ],
    colorOptions: [
      { code: "black", name: "Black", hexColor: "#1a1a1a" },
      { code: "purple", name: "Violet", hexColor: "#7c3aed" },
    ],
  },
];
