server.port=5000
spring.application.name=similarProductsDGG
spring.threads.virtual.enabled=true

# Cache Configuration
spring.cache.type=caffeine
spring.cache.cache-names=similarIds,productDetails
spring.cache.caffeine.spec=expireAfterWrite=5m,maximumSize=500

# External API Configuration
external.api.url=http://localhost:3001

# Logging Configuration
logging.level.reactor.netty.http.client=ERROR
